name: Test Download

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Chrome
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver

      - name: Install Python packages
        run: pip install selenium

      - name: Run script
        env:
          SITE_USERNAME: ${{ secrets.SITE_USERNAME }}
          SITE_PASSWORD: ${{ secrets.SITE_PASSWORD }}
        run: python script.py
